### ISSUE TITLE
jsdom 4.x onward only works on io.js, not Node.js

### ISSUE THREAD

**Issue by michel-kraemer** [michaelmcmillan/citeproc-node-iojs#1]
Thanks for this package. I'd really love to use it, but I get the following error message under Node 0.12:

```
jsdom 4.x onward only works on io.js, not Node.js
```

The package's description says it will work under io.js and node. Am I doing something wrong?

Thanks,
Michel

**Comment by michel-kraemer** [comment]
Did you have a look at https://github.com/zotero/citeproc-node? They are able to run citeproc-js without jsdom. They do this by converting all styles and locales to JSON with a small Python script. Works like a charm.

**Comment by theunexpected1** [comment]
importing older jsdom in package explicitly could resolve the issue
`"jsdom": ">= 0.1.23 < 4.0.0"`

**Comment by williamstein** [comment]
Using jsdom < 4.0.0 solved this for me.

**Comment by avialle** [comment]
why don't you simply install io.js ?

**Comment by rgubby** [comment]
If you're stuck on node < 4.x (AWS lambda for example) then the following worked for me in my package.json file

```
"scripts": {
  "postinstall": "cd node_modules/citeproc && npm install jsdom@3.1.2 && cd ../.."
}
```

**Comment by fbennett** [comment]
There will be some reshuffling of `citeproc` packages in `npm` over the weekend (March 18-20, 2017). One step will be to recast the `citeproc` module (currently defined here) to provide a bare `CSL` object that can be included in other projects as a dependency (@michaelmcmillan granted permissions to make adjustments mid-year last year, but I've been slow to move on it). When the update goes into npm, I'll file a deprecation notice pointing at a project that implements a framework equivalent to that provided here.

**Comment by fbennett** [comment]
Meanwhile, one note in answer to this thread. The latest versions of `citeproc-js` accept serialized XML for style and locale input. It should be possible to drop any `jsdom` dependency from existing `node.js` and `io.js` deployments.

**Comment by michel-kraemer** [comment]
@fbennett Looking forward to this. Thanks.
